site_name: Raapoi Cluster Documentation
nav: 
  - Documentation: index.md
  - Support: support.md
  - Utilisation: ganglia.md

theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
      toc_depth: 2

extra_css: [extra.css]


- url: /vuwrc/
  static_files: static/doc/index.html
  upload: vuwrc/docs/index.html
- url: /vuwrc
  static_dir: static/vuwrc

  use_directory_urls: false